### ISSUE TITLE
[BE] (Linked to 612 admin) Let superAdmin add new admins

### ISSUE THREAD

**Issue by yuliiakucher** [ita-social-projects/horondi_client_be#608]
In user module, we have method registerAdmin and confirmAdmin. You should get token from first method and implement functionality in confrimAdmin for finish registering admin. If superadmin wants to create new superadmin, they should enter code (that they get by email)

**Comment by twihell** [comment]
![mail with confirmation code](https://user-images.githubusercontent.com/14165251/114277760-3ea6e000-9a35-11eb-810a-0e1863e11dd4.PNG)


When you click on the button or on the link, you get redirected to the page with all users, but not to the form where we can paste the code itself. But maybe there is no need to have a link or button in this superadmin confirmation email at all? Because we already have an open page with a form to enter the code from the email. So it's enough to just go to the confirmation email, copy the code, return to the page with an open admin creation form and paste it in the form.

So my suggestion is to only have a code in the email. That's all. What do you think?
